const listKhodam = [
	"Nasi Uduk",
	"Sari Roti Beton",
	"Ban Serep",
	"Indomie Basi",
	"Pepes Tai",
	"Cilok Segitiga",
	"Kupu-kupu Emas",
	"Taplak Meja",
	"Lele Kayang",
	"Tutup Termos",
	"Kuntilanak Tobrut",
	"Elang Jawa",
	"Jarum Pentul",
	"Buaya Jantan",
	"Buaya Betina",
	"Monyet Pemalas",
	"Jarjit Pohon",
	"Nasi Kucing",
	"Lele Birahi",
	"Buaya Sunda",
	"Monyet Pemarah",
	"Fizi",
	"Kucing Julid",
];
export default listKhodam;